module.exports = {
    // TOKEN OF DISCORD APPLICATION
    TOKEN: 'NDIxNDAyODgwNDE1NzYwMzg1.Xrg_nA.vELska2uAKhz9q6EeouF9Bngcbc',
    // SERVER ID
    SERVER_ID: '639291443537641492',
    // CHANNEL FOR INFO MESSAGES
    TEXT_CH: '',
    // CHANNEL FOR RADIO STREAM
    VOICE_CH: '709101467604222072',
    // URL TO RADIO STREAM (Icecast/SHOUTcast)
    STREAM: 'http://icecast.skyrock.net/s/natio_mp3_128k',
    // DISABLE NP COMMAND
    DISABLENP: false,
    // YOUTUBE DATA API KEY
    YOUTUBE_KEY: '',
    // USERAGENT TO USE FOR CONNECTION
    USER_AGENT: '',
    // MINIMUM RANK NAME FOR PLAYRADIO COMMAND
    PLAYRADIO_MINRANK: '',
    // MINIMUM RANK NAME TO FORCE PLAYRADIO COMMAND
    PLAYRADIO_MINRANK_FORCE: '',
    // SEND MORE DEBUG MESSAGES
    DEBUG: false
};