module.exports = {
    // TOKEN OF DISCORD APPLICATION
    TOKEN: 'NjQxMDYzNzE0NzU3NDEwODE3.XrragA.wIKJs0Rg65yMSE9yz5Cno42Fjcg',
    // SERVER ID
    SERVER_ID: '690946371800268812',
    // CHANNEL FOR INFO MESSAGES
    TEXT_CH: '',
    // CHANNEL FOR RADIO STREAM
    VOICE_CH: '696429399561601166',
    // URL TO RADIO STREAM (Icecast/SHOUTcast)
    STREAM: 'http://icecast.skyrock.net/s/natio_mp3_128k',
    // DISABLE NP COMMAND
    DISABLENP: false,
    // YOUTUBE DATA API KEY
    YOUTUBE_KEY: '',
    // USERAGENT TO USE FOR CONNECTION
    USER_AGENT: '',
    // MINIMUM RANK NAME FOR PLAYRADIO COMMAND
    PLAYRADIO_MINRANK: '',
    // MINIMUM RANK NAME TO FORCE PLAYRADIO COMMAND
    PLAYRADIO_MINRANK_FORCE: '',
    // SEND MORE DEBUG MESSAGES
    DEBUG: false
};